apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpha-app
  namespace: team-alpha
  labels:
    team: alpha
    cost-centre: engineering
    app: alpha-app
    environment: demo
    cluster: kubecost-secondary
spec:
  replicas: 3
  selector:
    matchLabels:
      app: alpha-app
  template:
    metadata:
      labels:
        team: alpha
        cost-centre: engineering
        app: alpha-app
        environment: demo
        cluster: kubecost-secondary
    spec:
      containers:
      - name: app
        image: nginx:alpine
        resources:
          requests:
            cpu: 150m
            memory: 192Mi
          limits:
            cpu: 300m
            memory: 384Mi
---
apiVersion: v1
kind: Service
metadata:
  name: alpha-app
  namespace: team-alpha
  labels:
    team: alpha
    cost-centre: engineering
    app: alpha-app
spec:
  selector:
    app: alpha-app
  ports:
  - port: 80
    targetPort: 80
